version: '3'

services:
  postgres:
    image: postgres:16.0
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  neon-proxy:
    build:
      context: ./docker/neon-proxy/
      dockerfile: Dockerfile
    environment:
      PG_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - '4444:4444'
    depends_on:
      - postgres

volumes:
  db_data: