version: '3'

services:
  db:
    image: neondatabase/neon
    restart: always
    volumes:
      - ./db:/var/lib/neon/data
    environment:
      NEON_PASSWORD: ${POSTGRES_PASSWORD}
      NEON_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: NeonDB
    tty: true
